### ISSUE TITLE
Authentication Warning

### ISSUE THREAD

**Issue by jeremymeyers** [orioncrocker/spotify_images#2]
I believe spot may have changed their API authentication stuff because i'm getting a 401 error when trying to pull from a URL.

(ive added ID and secret to config.py)

**Comment by orioncrocker** [comment]
Thanks for letting me know! I've updated the codebase to fix the issue.
Let me know if you find any more issues.

**Comment by jeremymeyers** [comment]
apparently still happening (i did update my local clone).  i will double check my API settings too.


    ~/Documents/GitHub/spotify_images   master ⇣2 !1 ?1  python3 main.py "https://open.spotify.com/playlist/2YekdozcgWTiXh2vGoJ6ii?si=0f87917738a54161"
HTTP Error for GET to https://api.spotify.com/v1/playlists/2YekdozcgWTiXh2vGoJ6ii with Params: {'fields': 'name,tracks.items.track.album.name,tracks.items.track.album.images', 'market': 'US', 'additional_types': 'track'} returned 400 due to Only valid bearer authentication supported
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.spotify.com/v1/playlists/2YekdozcgWTiXh2vGoJ6ii?fields=name%2Ctracks.items.track.album.name%2Ctracks.items.track.album.images&market=US&additional_types=track

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jeremymeyers/Documents/GitHub/spotify_images/main.py", line 41, in <module>
    main()
  File "/Users/jeremymeyers/Documents/GitHub/spotify_images/main.py", line 34, in main
    directory = images.get_images(args.url, directory=args.directory, verbose=args.verbose, zip_this=args.zip)
  File "/Users/jeremymeyers/Documents/GitHub/spotify_images/images.py", line 42, in get_images
    results = api.get_playlist(url)
  File "/Users/jeremymeyers/Documents/GitHub/spotify_images/api.py", line 34, in get_playlist
    return spotify.playlist(url, fields='name,tracks.items.track.album.name,tracks.items.track.album.images', market='US')
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 617, in playlist
    return self._get(
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 297, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/usr/local/lib/python3.9/site-packages/spotipy/client.py", line 267, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/playlists/2YekdozcgWTiXh2vGoJ6ii?fields=name%2Ctracks.items.track.album.name%2Ctracks.items.track.album.images&market=US&additional_types=track:
 Only valid bearer authentication supported, reason: None
