### ISSUE TITLE
Index Out Of Bounds when geenerating collage

### ISSUE THREAD

**Issue by jeremymeyers** [orioncrocker/spotify_images#4]
(i know you said you were thinking of redoing this in JS so dont want to bombard you with stuff, but since you requested i let you know if anything else is broken.. ;) )
"
python3 main.py -vc "https://open.spotify.com/playlist/2YekdozcgWTiXh2vGoJ6ii?si=0f87917738a54161"
playlist found, downloading...
Name: Jeremy's Top Albums of 2017
Type: playlist
0 saved to results/jeremy's_top_albums_of_2017
Total unique pictures: 11
Rows: 3	Cols: 4
Traceback (most recent call last):
  File "/Users/jeremymeyers/Documents/GitHub/spotify_images/main.py", line 41, in <module>
    main()
  File "/Users/jeremymeyers/Documents/GitHub/spotify_images/main.py", line 37, in main
    collage.make_collage(directory=directory, verbose=args.verbose)
  File "/Users/jeremymeyers/Documents/GitHub/spotify_images/collage.py", line 58, in make_collage
    new_row.paste(pics[count], (x_offset,0))
IndexError: list index out of range
"

**Comment by Patitotective** [comment]
Add this under `for col in range (0, cols):` in `collage.py` in line 57:
```py
      if count >= len(pics):
        break
```

**Comment by orioncrocker** [comment]
Issue has been fixed: https://github.com/orioncrocker/spotify_images/commit/69e901620f6682e61acd713f847721c6f0be237c

```
playlist found, downloading...
Name: Send it brother
Type: playlist
results/send_it_brother/my_favourite_stories.jpeg
results/send_it_brother/running_up_that_hill.jpeg
results/send_it_brother/lettin'_go_hardstyle_(deluxe).jpeg
results/send_it_brother/this_means_war.jpeg
results/send_it_brother/repeater.jpeg
results/send_it_brother/nightwolf:_survive_the_megadome.jpeg
results/send_it_brother/with_oden_on_our_side.jpeg
results/send_it_brother/where_is_my_mind.jpeg
results/send_it_brother/out_of_body.jpeg
results/send_it_brother/who_else.jpeg
results/send_it_brother/regenerator.jpeg
11 saved to results/send_it_brother
Total unique pictures: 11
Rows: 3	Cols: 3
Collage saved as: results/send_it_brother.jpeg

```
